name: test

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"' # create TTY so that -t STDIN works
    strategy:
      matrix:
        perl-version:
          - '5.8-buster'
          - '5.10-buster'
          - 'latest'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          perl App-cpanminus/cpanm -nq App::cpanminus
          cpanm -nq LWP::Protocol::https
          (cd App-cpanminus && cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .)
          (cd Menlo && cpanm -nq --installdeps --with-develop --with-recommends --with-suggests .)
      - name: Run Tests
        run: (cd App-cpanminus && for i in 1 2 3 4 5 6 7 8 9 10; do prove -lrv xt/verify_signature.t; done )
